# fly.toml app configuration file generated for wetubekjh on 2023-06-22T00:21:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wetubekjh"
primary_region = "nrt"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
