# fly.toml app configuration file generated for wetubekjh46 on 2023-06-24T16:26:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wetubekjh46"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
